#!/usr/bin/env python
# ruff: noqa: F821

import methods

env = SConscript("./godot-cpp/SConstruct")
env.__class__.disable_warnings = methods.disable_warnings

env.Append(CPPDEFINES=["GDEXTENSION"])
env.Append(CPPPATH=["../", "../clips_core"])

sources = Glob("../*.cpp") + Glob("../clips_core/*.cpp")

if env["platform"] == "macos":
    methods.write_macos_plist(
        f"./bin/libgd_rules.macos.{env['target']}.framework",
        f"libgd_rules.macos.{env['target']}",
        "org.godotengine.gd_rules",
        "GD Rules",
    )
    library = env.SharedLibrary(
        f"./bin/libgd_rules.macos.{env['target']}.framework/libgd_rules.macos.{env['target']}",
        source=sources,
    )
else:
    library = env.SharedLibrary(
        f"./bin/libgd_rules{env['suffix']}{env['SHLIBSUFFIX']}",
        source=sources,
    )

Default(library)

methods.prepare_timer()
